/// Flutter icons My_icons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  My_icons
///      fonts:
///       - asset: fonts/My_icons.ttf
///
///
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Brandico, (C) 2012 by Vitaly Puzrin
///         Author:    Crowdsourced, for Fontello project
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:
///
import 'package:flutter/widgets.dart';

// ignore: camel_case_types
class My_icons {
  My_icons._();

  static const _kFontFam = 'My_icons';

  static const IconData feedbacks = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData duvidas = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData contato = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData whats = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData insta = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData lanche_footer = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData combo_footer = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData bebida_footer = IconData(0xe807, fontFamily: _kFontFam);
  static const IconData casa_footer = IconData(0xe808, fontFamily: _kFontFam);
  static const IconData promo = IconData(0xe809, fontFamily: _kFontFam);
  static const IconData instagram_square =
      IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData instagram = IconData(0xf16d, fontFamily: _kFontFam);
  static const IconData whatsapp = IconData(0xf232, fontFamily: _kFontFam);
  static const IconData instagram_2 = IconData(0xf31e, fontFamily: _kFontFam);
  static const IconData instagram_filled =
      IconData(0xf31f, fontFamily: _kFontFam);
  static const IconData whatsapp_square =
      IconData(0xf40c, fontFamily: _kFontFam);
}
